### ISSUE TITLE
Switch from make to mage

### ISSUE THREAD

**Issue by carolynvs** [getporter/skeletor#28]
We have been migrating away from make to mage throughout the Porter codebase. It's greatly simplified the file because it can reuse logic from upstream Porter. Let's rewrite the makefile to be a magefile, similar to the other mixins:

https://github.com/getporter/docker-compose-mixin/pull/23

**Comment by troy0820** [comment]
@schristoff this may be able to be closed.

**Comment by kichristensen** [comment]
Closed as mage is already used in this repo
